In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame
import matplotlib as plt
import seaborn as sns
import yfinance as yf
%matplotlib inline

In [2]:
import pandas_datareader.data as wb

In [3]:
from datetime import datetime

In [4]:
from __future__ import division

In [5]:
allASXstocks = pd.read_csv('ASXListedCompanies.csv')

In [6]:
allASXstocks

,Company name,ASX code,GICS industry group,YF ASX code
0,MOQ LIMITED,MOQ,Software & Services,MOQ.AX
1,1300 SMILES LIMITED,ONT,Health Care Equipment & Services,ONT.AX
2,1414 DEGREES LIMITED,14D,Capital Goods,14D.AX
3,1ST GROUP LIMITED,1ST,Health Care Equipment & Services,1ST.AX
4,333D LIMITED,T3D,Commercial & Professional Services,T3D.AX
...,...,...,...,...
2150,ZINC OF IRELAND NL,ZMI,Materials,ZMI.AX
2151,ZIP CO LIMITED.,Z1P,Diversified Financials,Z1P.AX
2152,ZIPTEL LIMITED,ZIP,Telecommunication Services,ZIP.AX
2153,ZOONO GROUP LIMITED,ZNO,Materials,ZNO.AX
2154,ZYBER HOLDINGS LTD,ZYB,Software & Services,ZYB.AX

In [7]:
allASXstocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2155 entries, 0 to 2154
Data columns (total 4 columns):
Company name           2155 non-null object
ASX code               2155 non-null object
GICS industry group    2155 non-null object
YF ASX code            2155 non-null object
dtypes: object(4)
memory usage: 67.5+ KB

In [8]:
Examined_stocks = allASXstocks[allASXstocks['GICS industry group'] == 'Banks']

In [9]:
Examined_stocks

,Company name,ASX code,GICS industry group,YF ASX code
230,AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED,ANZ,Banks,ANZ.AX
239,AUSTRALIAN FINANCE GROUP LTD,AFG,Banks,AFG.AX
258,AUSWIDE BANK LTD,ABA,Banks,ABA.AX
278,BANK OF QUEENSLAND LIMITED.,BOQ,Banks,BOQ.AX
300,BENDIGO AND ADELAIDE BANK LIMITED,BEN,Banks,BEN.AX
342,BNK BANKING CORPORATION LIMITED,BBC,Banks,BBC.AX
499,COMMONWEALTH BANK OF AUSTRALIA.,CBA,Banks,CBA.AX
807,GENWORTH MORTGAGE INSURANCE AUSTRALIA LIMITED,GMA,Banks,GMA.AX
873,HEARTLAND GROUP HOLDINGS LIMITED,HGH,Banks,HGH.AX
1052,KINA SECURITIES LIMITED,KSL,Banks,KSL.AX
1286,MORTGAGE CHOICE LIMITED,MOC,Banks,MOC.AX
1304,MYSTATE LIMITED,MYS,Banks,MYS.AX
1306,N1 HOLDINGS LIMITED,N1H,Banks,N1H.AX
1315,NATIONAL AUSTRALIA BANK LIMITED,NAB,Banks,NAB.AX
1650,RESIMAC GROUP LTD,RMC,Banks,RMC.AX
2046,VIRGIN MONEY UK PLC,VUK,Banks,VUK.AX
2097,WESTPAC BANKING CORPORATION,WBC,Banks,WBC.AX
2138,YELLOW BRICK ROAD HOLDINGS LIMITED,YBR,Banks,YBR.AX

In [10]:
Examined_list = Examined_stocks['YF ASX code'].tolist()

In [11]:
Examined_list

['ANZ.AX',
 'AFG.AX',
 'ABA.AX',
 'BOQ.AX',
 'BEN.AX',
 'BBC.AX',
 'CBA.AX',
 'GMA.AX',
 'HGH.AX',
 'KSL.AX',
 'MOC.AX',
 'MYS.AX',
 'N1H.AX',
 'NAB.AX',
 'RMC.AX',
 'VUK.AX',
 'WBC.AX',
 'YBR.AX']

In [12]:
end = datetime.now()
start = datetime(end.year-5, end.month, end.day)

In [13]:
for stock in Examined_list:
    stock = wb.DataReader(stock, 'yahoo', start, end)

In [15]:
ANZ

NameError: name 'ANZ' is not defined